trigger:
  branches:
    include:
      - master  # Update with your branch name

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'  # Update with your desired build configuration
  imageName: hospital_appointment_booking_system:latest

steps:
 - task: Docker@2
   displayName: Build an image
   inputs:
     repository: $(imageName)
     command: build
     Dockerfile: Dockerfile